//*
//* DO NOT EDIT THIS FILE 
//* This file is generated from file ./../me.stec.admin/sql/table/100902_00-12_div_faculty.sql 
//* Edit that file if it is necessary and run me.stec.jet.Main for regeneration
//* (me.ste.jet -> right click -> Run As -> Java Application -> Main - me.stec.jet)
//* or create an inherent class to extend the functionality.
//*

package me.stec.admin.logic.org;

import java.math.BigDecimal;



import me.stec.admin.iface.IVal;
import me.stec.admin.logic.DbField;
import me.stec.admin.logic.AItemList;

/**
* Список Факультетов
*/
public class FacultyList extends 
AItemList{

	@Override
	public String getDbSchemeName(){
		return "DIV_FACULTY";
	}
	
	@Override
	public boolean getDbSchemeReadOnly(){
		return true;
	}

	@Override
	protected String getLoadQuery() {
		return FacultyList.sLoadQuery;
	}
	@Override
	protected String getLoadComboQuery(){
		return FacultyList.sLoadComboQuery;
	}
	@Override
	protected String getDeleteQuery() {
		return FacultyList.sDeleteQuery;
	}
	/**
	 * NOTE: m_def should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static final FacultyList m_def = new FacultyList();
//	static{
//		m_def.sOrderBy = m_def.sOrderByCombo = " ORDER BY " + m_def.getId().getDbColumnName();
//	}
	
	/**
	 * NOTE: sLoadQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static String sLoadQuery		= m_def.getLoadQueryString();
	/**
	 * NOTE: sLoadComboQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static String sLoadComboQuery = m_def.getLoadComboQueryString();
	/**
	 * NOTE: sDeleteQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static String sDeleteQuery	= m_def.getDeleteQueryString();
	
		public FacultyList(){
			this(false,		0);
		}
		public FacultyList(boolean bDistinct){
			this(bDistinct, 0);//0 (or negative int) means no limit
		}
		public FacultyList(boolean bDistinct, int iLimit){
			super(new IVal[]{
				new DbField<BigDecimal, Faculty.zzzIdAttr>(null, Faculty.zzzIdAttr.getInstance()),
				new DbField<String, Faculty.zzzNameAttr>(null, Faculty.zzzNameAttr.getInstance()),
				new DbField<String, Faculty.zzzTechNameAttr>(null, Faculty.zzzTechNameAttr.getInstance()),
				new DbField<String, Faculty.zzzEngNameAttr>(null, Faculty.zzzEngNameAttr.getInstance()),
				new DbField<BigDecimal, Faculty.zzzIdDivisionAttr>(null, Faculty.zzzIdDivisionAttr.getInstance())
			});
			
			super.bDistinct 	= bDistinct;
			super.iLimit		= iLimit;
			
			if (null == m_def)	return;
			
			super.getListHeader().addAll(m_def.getListHeader());
			super.sOrderBy		= m_def.sOrderBy;
			super.sOrderByCombo	= m_def.sOrderByCombo;
			
		}

		@Override
		public Faculty getItemDef(){
			return Faculty.getDef();
		}
		
		@SuppressWarnings("unchecked")
		public DbField<BigDecimal, Faculty.zzzIdAttr> getId() { return (DbField<BigDecimal, Faculty.zzzIdAttr>)super.val[0]; } 
		public void setId(DbField<BigDecimal, Faculty.zzzIdAttr> value) { super.val[0].setVal(value.getVal());}
		public void setId(BigDecimal value) { super.val[0].setVal(value);}
		 
		@SuppressWarnings("unchecked")
		public DbField<String, Faculty.zzzNameAttr> getName() { return (DbField<String, Faculty.zzzNameAttr>)super.val[1]; } 
		public void setName(DbField<String, Faculty.zzzNameAttr> value) { super.val[1].setVal(value.getVal());}
		public void setName(String value) { super.val[1].setVal(value);}
		 
		@SuppressWarnings("unchecked")
		public DbField<String, Faculty.zzzTechNameAttr> getTechName() { return (DbField<String, Faculty.zzzTechNameAttr>)super.val[2]; } 
		public void setTechName(DbField<String, Faculty.zzzTechNameAttr> value) { super.val[2].setVal(value.getVal());}
		public void setTechName(String value) { super.val[2].setVal(value);}
		 
		@SuppressWarnings("unchecked")
		public DbField<String, Faculty.zzzEngNameAttr> getEngName() { return (DbField<String, Faculty.zzzEngNameAttr>)super.val[3]; } 
		public void setEngName(DbField<String, Faculty.zzzEngNameAttr> value) { super.val[3].setVal(value.getVal());}
		public void setEngName(String value) { super.val[3].setVal(value);}
		 
		@SuppressWarnings("unchecked")
		public DbField<BigDecimal, Faculty.zzzIdDivisionAttr> getIdDivision() { return (DbField<BigDecimal, Faculty.zzzIdDivisionAttr>)super.val[4]; } 
		public void setIdDivision(DbField<BigDecimal, Faculty.zzzIdDivisionAttr> value) { super.val[4].setVal(value.getVal());}
		public void setIdDivision(BigDecimal value) { super.val[4].setVal(value);}
		 
}
