//*
//* DO NOT EDIT THIS FILE 
//* This file is generated from file ./../me.stec.admin/sql/table/100902_00-13_div_kurs.sql 
//* Edit that file if it is necessary and run me.stec.jet.Main for regeneration
//* (me.ste.jet -> right click -> Run As -> Java Application -> Main - me.stec.jet)
//* or create an inherent class to extend the functionality.
//*

package me.stec.admin.logic.org;

import java.math.BigDecimal;



import me.stec.admin.iface.IVal;
import me.stec.admin.logic.DbField;
import me.stec.admin.logic.AItemList;

/**
* Список Курсов
*/
public class KursList extends 
AItemList{

	@Override
	public String getDbSchemeName(){
		return "DIV_KURS";
	}
	
	@Override
	public boolean getDbSchemeReadOnly(){
		return true;
	}

	@Override
	protected String getLoadQuery() {
		return KursList.sLoadQuery;
	}
	@Override
	protected String getLoadComboQuery(){
		return KursList.sLoadComboQuery;
	}
	@Override
	protected String getDeleteQuery() {
		return KursList.sDeleteQuery;
	}
	/**
	 * NOTE: m_def should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static final KursList m_def = new KursList();
//	static{
//		m_def.sOrderBy = m_def.sOrderByCombo = " ORDER BY " + m_def.getId().getDbColumnName();
//	}
	
	/**
	 * NOTE: sLoadQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static String sLoadQuery		= m_def.getLoadQueryString();
	/**
	 * NOTE: sLoadComboQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static String sLoadComboQuery = m_def.getLoadComboQueryString();
	/**
	 * NOTE: sDeleteQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static String sDeleteQuery	= m_def.getDeleteQueryString();
	
		public KursList(){
			this(false,		0);
		}
		public KursList(boolean bDistinct){
			this(bDistinct, 0);//0 (or negative int) means no limit
		}
		public KursList(boolean bDistinct, int iLimit){
			super(new IVal[]{
				new DbField<BigDecimal, Kurs.zzzIdAttr>(null, Kurs.zzzIdAttr.getInstance()),
				new DbField<String, Kurs.zzzNameAttr>(null, Kurs.zzzNameAttr.getInstance())
			});
			
			super.bDistinct 	= bDistinct;
			super.iLimit		= iLimit;
			
			if (null == m_def)	return;
			
			super.getListHeader().addAll(m_def.getListHeader());
			super.sOrderBy		= m_def.sOrderBy;
			super.sOrderByCombo	= m_def.sOrderByCombo;
			
		}

		@Override
		public Kurs getItemDef(){
			return Kurs.getDef();
		}
		
		@SuppressWarnings("unchecked")
		public DbField<BigDecimal, Kurs.zzzIdAttr> getId() { return (DbField<BigDecimal, Kurs.zzzIdAttr>)super.val[0]; } 
		public void setId(DbField<BigDecimal, Kurs.zzzIdAttr> value) { super.val[0].setVal(value.getVal());}
		public void setId(BigDecimal value) { super.val[0].setVal(value);}
		 
		@SuppressWarnings("unchecked")
		public DbField<String, Kurs.zzzNameAttr> getName() { return (DbField<String, Kurs.zzzNameAttr>)super.val[1]; } 
		public void setName(DbField<String, Kurs.zzzNameAttr> value) { super.val[1].setVal(value.getVal());}
		public void setName(String value) { super.val[1].setVal(value);}
		 
}
