//*
//* DO NOT EDIT THIS FILE 
//* This file is generated from file ./../me.stec.admin/sql/table/100902_00-18_div_speciality.sql 
//* Edit that file if it is necessary and run me.stec.jet.Main for regeneration
//* (me.ste.jet -> right click -> Run As -> Java Application -> Main - me.stec.jet)
//* or create an inherent class to extend the functionality.
//*

package me.stec.admin.logic.org;

import java.sql.SQLException;

import java.math.BigDecimal;

import com.google.common.collect.BiMap;
import com.google.common.collect.HashBiMap;


import me.stec.admin.iface.IAttr;
import me.stec.admin.iface.IVal;
import me.stec.admin.logic.DbField;
import me.stec.admin.logic.AItem;
import me.stec.admin.db.Privs;

/**
* Специальность
*/
public class Speciality extends 
AItem{
	@Override
	public String getDbSchemeName(){
		return "DIV_SPECIALITY";
	}

	@Override
	public boolean getDbSchemeReadOnly(){
		return true;
	}

	@Override
	public BigDecimal getID() {
		return this.getId().getValue();
	}
	@Override
	public void setID(BigDecimal id) {
		this.getId().setValue(id);
	} 

	@Override
	public String getIdDbColumnName() {
		return this.getId().getDbColumnName();
	}

	@Override
	protected String getLoadQuery() {
		return Speciality.sLoadQuery;
	} 
	@Override
	protected String getInsertQuery() {
		return Speciality.sInsertQuery;
	} 
	@Override
	protected String getUpdateQuery() {
		return Speciality.sUpdateQuery;
	} 
	@Override
	protected String getDeleteQuery() {
		return Speciality.sDeleteQuery;
	} 
	
	protected static final BiMap<String, Integer> columnNumber = HashBiMap.create();
	@Override
	protected BiMap<String, Integer> getColumnNumber() {
		return columnNumber;
	}
	
	/**
	 * NOTE: field m_def SHOULD NEVER BE CHANGED (as well as it's state)  
	 */
	private static final Speciality m_def = new Speciality();  
	/**
	 * NOTE: sLoadQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	static{
		FillColumnData(m_def);
	}
	
	/**
	 * NOTE: sLoadQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	private static String sLoadQuery	= m_def.getLoadQueryString();
	/**
	 * NOTE: sInsertQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	private static String sInsertQuery	= m_def.getInsertQueryString();
	/**
	 * NOTE: sUpdateQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	private static String sUpdateQuery	= m_def.getUpdateQueryString();
	/**
	 * NOTE: sDeleteQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	private static String sDeleteQuery	= m_def.getDeleteQueryString();

	
	@Override
	public String getLastIdQuery(){
		return "SELECT sq_div_speciality_i.currval FROM DUAL";
	}

	private static final class Inner{
		private static boolean canSelect = false;
		private static boolean canInsert = false;
		private static boolean canUpdate = false;
		private static boolean canDelete = false;
		static{
			Privs.setup(m_def);
		}
	}

	@Override
	public void setCanSelect(boolean canSelect){
		Speciality.Inner.canSelect = canSelect;
	}
	@Override
	public boolean canSelect(){
		return 	Speciality.Inner.canSelect;
	}
	
	@Override
	public void setCanInsert(boolean canInsert){
		Speciality.Inner.canInsert = canInsert;
	}
	@Override
	public boolean canInsert(){
		return 	Speciality.Inner.canInsert;
	}

	@Override
	public void setCanUpdate(boolean canUpdate){
		Speciality.Inner.canUpdate = canUpdate;
	}
	@Override
	public boolean canUpdate(){
		return 	Speciality.Inner.canUpdate;
	}

	@Override
	public void setCanDelete(boolean canDelete){
		Speciality.Inner.canDelete = canDelete;
	}
	@Override
	public boolean canDelete(){
		return 	Speciality.Inner.canDelete;
	}
	
		
		public Speciality(){
			super(new IVal[]{
				new DbField<BigDecimal, zzzIdAttr>(null, zzzIdAttr.getInstance()),
				new DbField<String, zzzNameAttr>(null, zzzNameAttr.getInstance()),
				new DbField<String, zzzTechNameAttr>(null, zzzTechNameAttr.getInstance()),
				new DbField<BigDecimal, zzzIdDivisionAttr>(null, zzzIdDivisionAttr.getInstance())
			});
		}
		public Speciality(BigDecimal id, boolean forUpdate)  throws SQLException {
			this();
			this.setID(id);
			load(forUpdate);
		}

		public static Speciality getDef(){
			return Speciality.m_def;
		}
		
		public static final class zzzIdAttr extends IAttr{
			private zzzIdAttr(){}
			private static final zzzIdAttr m_Instance = new zzzIdAttr();
			public static zzzIdAttr getInstance() {return m_Instance; }
			public String           getName()				{ return "Id";  }
			public String           getDbColumnName()		{ return "DIV_SPECIALITY_ID"; }  
			public String           getCaption()			{ return "ИН специальности"; }  
			public boolean          getDbReadOnly()			{ return true; }  
			public boolean          getDbIsCombo()			{ return true; }  
			public boolean          getDbIsNotNull()		{ return true; }         }
		@SuppressWarnings("unchecked")
		public DbField<BigDecimal, zzzIdAttr> getId() { return (DbField<BigDecimal, zzzIdAttr>)super.val[0]; } 
		public void setId(DbField<BigDecimal, zzzIdAttr> value) { super.val[0].setVal(value.getVal());} 
		public void setId(BigDecimal value) { super.val[0].setVal(value);}
		
		
		public static final class zzzNameAttr extends IAttr{
			private zzzNameAttr(){}
			private static final zzzNameAttr m_Instance = new zzzNameAttr();
			public static zzzNameAttr getInstance() {return m_Instance; }
			public String           getName()				{ return "Name";  }
			public String           getDbColumnName()		{ return "NAME"; }  
			public String           getCaption()			{ return "Название специальности"; }  
			public boolean          getDbIsCombo()			{ return true; }  
			public boolean          isString()				{ return true; }         }
		@SuppressWarnings("unchecked")
		public DbField<String, zzzNameAttr> getName() { return (DbField<String, zzzNameAttr>)super.val[1]; } 
		public void setName(DbField<String, zzzNameAttr> value) { super.val[1].setVal(value.getVal());} 
		public void setName(String value) { super.val[1].setVal(value);}
		public IVal getComboName() { return getName(); }
		
		public static final class zzzTechNameAttr extends IAttr{
			private zzzTechNameAttr(){}
			private static final zzzTechNameAttr m_Instance = new zzzTechNameAttr();
			public static zzzTechNameAttr getInstance() {return m_Instance; }
			public String           getName()				{ return "TechName";  }
			public String           getDbColumnName()		{ return "TECH_NAME"; }  
			public String           getCaption()			{ return "Техническое название специальности"; }  
			public boolean          getDbLoadableInList()	{ return false; }  
			public boolean          isString()				{ return true; }         }
		@SuppressWarnings("unchecked")
		public DbField<String, zzzTechNameAttr> getTechName() { return (DbField<String, zzzTechNameAttr>)super.val[2]; } 
		public void setTechName(DbField<String, zzzTechNameAttr> value) { super.val[2].setVal(value.getVal());} 
		public void setTechName(String value) { super.val[2].setVal(value);}
		
		
		public static final class zzzIdDivisionAttr extends IAttr{
			private zzzIdDivisionAttr(){}
			private static final zzzIdDivisionAttr m_Instance = new zzzIdDivisionAttr();
			public static zzzIdDivisionAttr getInstance() {return m_Instance; }
			public String           getName()				{ return "IdDivision";  }
			public String           getDbColumnName()		{ return "DIVISION_ID"; }  
			public String           getCaption()			{ return "ИН Подразделения"; }  
			public boolean          getDbLoadableInList()	{ return false; }  
			public boolean          getDbReadOnly()			{ return true; }         }
		@SuppressWarnings("unchecked")
		public DbField<BigDecimal, zzzIdDivisionAttr> getIdDivision() { return (DbField<BigDecimal, zzzIdDivisionAttr>)super.val[3]; } 
		public void setIdDivision(DbField<BigDecimal, zzzIdDivisionAttr> value) { super.val[3].setVal(value.getVal());} 
		public void setIdDivision(BigDecimal value) { super.val[3].setVal(value);}
		
		
}
