//*
//* DO NOT EDIT THIS FILE 
//* This file is generated from file ./../me.stec.admin/sql/table/100902_00-04_stec_user_cat.sql 
//* Edit that file if it is necessary and run me.stec.jet.Main for regeneration
//* (me.ste.jet -> right click -> Run As -> Java Application -> Main - me.stec.jet)
//* or create an inherent class to extend the functionality.
//*

package me.stec.admin.widget.provider;

import java.sql.SQLException;

import com.google.common.collect.BiMap;

import me.stec.admin.iface.IAttr;
import me.stec.admin.logic.AItemList;
import me.stec.admin.logic.user.StecUserCatList;

public class MPComboStecUserCat extends AMPCombo{
	private static AItemList aItemList = new StecUserCatList();

	private static final Combo1MP mp = new Combo1MP(aItemList);
	private static BiMap<String, Object> data;
	static{	try {data = mp.run().getRowList();} catch (SQLException e) {} }
	private static IAttr ia = aItemList.getItemDef().getComboName().getAttr(); 
	
	public BiMap<String, Object> getRowList() {	return data; };
	public Integer getTextLimit(){return ia.getDataLength();}
	
}
