//*
//* DO NOT EDIT THIS FILE 
//* This file is generated from file ./../me.stec.admin/sql/table/100902_00-04_stec_user_cat.sql 
//* Edit that file if it is necessary and run me.stec.jet.Main for regeneration
//* (me.ste.jet -> right click -> Run As -> Java Application -> Main - me.stec.jet)
//* or create an inherent class to extend the functionality.
//*

package me.stec.admin.logic.user;

import java.math.BigDecimal;



import me.stec.admin.iface.IVal;
import me.stec.admin.logic.DbField;
import me.stec.admin.logic.AItemList;

/**
* Список Категория пользователяов
*/
public class StecUserCatList extends 
AItemList{

	@Override
	public String getDbSchemeName(){
		return "STEC_USER_CAT";
	}
	
	@Override
	public boolean getDbSchemeReadOnly(){
		return true;
	}

	@Override
	protected String getLoadQuery() {
		return StecUserCatList.sLoadQuery;
	}
	@Override
	protected String getLoadComboQuery(){
		return StecUserCatList.sLoadComboQuery;
	}
	@Override
	protected String getDeleteQuery() {
		return StecUserCatList.sDeleteQuery;
	}
	/**
	 * NOTE: m_def should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static final StecUserCatList m_def = new StecUserCatList();
//	static{
//		m_def.sOrderBy = m_def.sOrderByCombo = " ORDER BY " + m_def.getId().getDbColumnName();
//	}
	
	/**
	 * NOTE: sLoadQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static String sLoadQuery		= m_def.getLoadQueryString();
	/**
	 * NOTE: sLoadComboQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static String sLoadComboQuery = m_def.getLoadComboQueryString();
	/**
	 * NOTE: sDeleteQuery should NEVER be changed DYNAMICALLY, 
	 * only a static context is encouraged for any change  
	 */
	protected static String sDeleteQuery	= m_def.getDeleteQueryString();
	
		public StecUserCatList(){
			this(false,		0);
		}
		public StecUserCatList(boolean bDistinct){
			this(bDistinct, 0);//0 (or negative int) means no limit
		}
		public StecUserCatList(boolean bDistinct, int iLimit){
			super(new IVal[]{
				new DbField<BigDecimal, StecUserCat.zzzIdAttr>(null, StecUserCat.zzzIdAttr.getInstance()),
				new DbField<String, StecUserCat.zzzConstantAttr>(null, StecUserCat.zzzConstantAttr.getInstance()),
				new DbField<String, StecUserCat.zzzNameAttr>(null, StecUserCat.zzzNameAttr.getInstance())
			});
			
			super.bDistinct 	= bDistinct;
			super.iLimit		= iLimit;
			
			if (null == m_def)	return;
			
			super.getListHeader().addAll(m_def.getListHeader());
			super.sOrderBy		= m_def.sOrderBy;
			super.sOrderByCombo	= m_def.sOrderByCombo;
			
		}

		@Override
		public StecUserCat getItemDef(){
			return StecUserCat.getDef();
		}
		
		@SuppressWarnings("unchecked")
		public DbField<BigDecimal, StecUserCat.zzzIdAttr> getId() { return (DbField<BigDecimal, StecUserCat.zzzIdAttr>)super.val[0]; } 
		public void setId(DbField<BigDecimal, StecUserCat.zzzIdAttr> value) { super.val[0].setVal(value.getVal());}
		public void setId(BigDecimal value) { super.val[0].setVal(value);}
		 
		@SuppressWarnings("unchecked")
		public DbField<String, StecUserCat.zzzConstantAttr> getConstant() { return (DbField<String, StecUserCat.zzzConstantAttr>)super.val[1]; } 
		public void setConstant(DbField<String, StecUserCat.zzzConstantAttr> value) { super.val[1].setVal(value.getVal());}
		public void setConstant(String value) { super.val[1].setVal(value);}
		 
		@SuppressWarnings("unchecked")
		public DbField<String, StecUserCat.zzzNameAttr> getName() { return (DbField<String, StecUserCat.zzzNameAttr>)super.val[2]; } 
		public void setName(DbField<String, StecUserCat.zzzNameAttr> value) { super.val[2].setVal(value.getVal());}
		public void setName(String value) { super.val[2].setVal(value);}
		 
}
